app:
  title: Document Ingestion System
  version: 1.0.0
database:
  url: sqlite:///documents.db
message_bus:
  rabbitmq_host: localhost
  rabbitmq_port: 5672
  rabbitmq_user: guest
  rabbitmq_password: guest
  azure_openai_key: 
  azure_openai_api_version: 2024-08-01-preview
  azure_openai_endpoint: https://hexavarsity-secureapi.azurewebsites.net/api/azureai
  azure_openai_deployment: gpt-4


# AZURE_OPENAI_KEY=cb7f8503371e48b5
# AZURE_OPENAI_API_VERSION=2024-08-01-preview
# AZURE_OPENAI_ENDPOINT=https://hexavarsity-secureapi.azurewebsites.net/api/azureai
# AZURE_OPENAI_DEPLOYMENT=gpt-4o